### PR TITLE
Makes it more like fnaf world

### PR DESCRIPTION
**Pull request by jmxamongusmodder**
ALRIGHT HERES WHAT I DID:
Actual fnaf world warning screen + better title button (ripped from fnaf world itself)
Kind of remove the mods from the title screen (why not?)
Cam fixes (bro this mod has the worst cameras i've seen)
No more repeating when you click the menu buttons?
Actual readme

### CODE REVIEW

**Comment by friend-pixel** [comment]
Some of the stuff was going to be on an update, the character selection will be freeplay, rainbow is CUT but it's going to another version, the start button is the same as fnaf world, i actually have the fnaf world files, the warning screen was not accurate because we didnt want to, we made it that way because yeah.

**Comment by jmxamongusmodder** [comment]
> Some of the stuff was going to be on an update, the character selection will be freeplay, rainbow is CUT but it's going to another version, the start button is the same as fnaf world, i actually have the fnaf world files, the warning screen was not accurate because we didnt want to, we made it that way because yeah.

Alright but i am fixing those cameras
because there broken

**Comment by jmxamongusmodder** [comment]
> > Some of the stuff was going to be on an update, the character selection will be freeplay, rainbow is CUT but it's going to another version, the start button is the same as fnaf world, i actually have the fnaf world files, the warning screen was not accurate because we didnt want to, we made it that way because yeah.
> 
> Alright but i am fixing those cameras because there broken

also hey if you need some help with like cameras or other things then consider me
im good at stuff

**Comment by friend-pixel** [comment]
yeah thank u for the camera fix

**Comment by jmxamongusmodder** [comment]
> yeah thank u for the camera fix

also the buttons repeat twice on the main menu after selecting
i think i fixed it

**Comment by jmxamongusmodder** [comment]
making the new freeplay wish me luck

**Comment by friend-pixel** [comment]
BRO STOOOOP

**Comment by friend-pixel** [comment]
Friend#3231 ADD ME DAMN

**Comment by friend-pixel** [comment]
DUUUUDE

**Comment by jmxamongusmodder** [comment]
> DUUUUDE

hi

**Comment by friend-pixel** [comment]
ADD ME ON DISCORD PLEASE Friend#3231 Friend#3231

**Comment by jmxamongusmodder** [comment]
> Friend#3231

does this mean im hired

**Comment by jmxamongusmodder** [comment]
> > Friend#3231
> 
> does this mean im hired

sent im uh coltinthefurry

**Comment by Alt-Reality** [comment]
We changed the warning on purpose,  the start button is quite literally the same as ours, the mods thing changed nothing since theres no mods anyways, there's no point in adding the chica rainbow stuff straight from the game, we are doing our own later, the camera thing u did didn't do anything, apart from make the camera be further right after it shifts during freeplay. The read me change is useless, nobody reads the readme unless its a psych engine beginner learning how to use it. For the main menu, all your did was remove the tracing that tells you what is unlocked and whats not. At this point your making this mod be an actual fnaf world 2. Let this have some originality and hand made assets rather than stuff ripped from the game

**Comment by jmxamongusmodder** [comment]
alright im deleting my fork

**Comment by jmxamongusmodder** [comment]
thought you would at least take the camera fixes

**Comment by jmxamongusmodder** [comment]
> thought you would at least take the camera fixes

those were the most important as the cameras suck

**Comment by Alt-Reality** [comment]
> > thought you would at least take the camera fixes
> 
> those were the most important as the cameras suck

that's the thing, the camera fixes didn't change anything. at the start of a freeplay song the camera still moves into position, only now its further right, and hide more of fredbear

**Comment by Alt-Reality** [comment]
the issue isnt the cameras, its the cameras not starting at the right spot. don't know if this is because the engine version, but after the camera moves into position, its perfectly placed.

**Comment by jmxamongusmodder** [comment]
> the issue isnt the cameras, its the cameras not starting at the right spot. don't know if this is because the engine version, but after the camera moves into position, its perfectly placed.

just stop
im done.
ok?
IM DONE.

**Comment by Username2120** [comment]
> the issue isnt the cameras, its the cameras not starting at the right spot. don't know if this is because the engine version, but after the camera moves into position, its perfectly placed.

the camera in every song usually starts where gf is placed and where her camera is placed. that's probably why the camera doesn't start perfect.

**Comment by Alt-Reality** [comment]
> > the issue isnt the cameras, its the cameras not starting at the right spot. don't know if this is because the engine version, but after the camera moves into position, its perfectly placed.
> 
> the camera in every song usually starts where gf is placed and where her camera is placed. that's probably why the camera doesn't start perfect.

maybe. Ill check it out and probably fix it in a later update since I don't think its that major to fix right now

**Pull request closed without merging**
